version: "3"

services:
  app:
    container_name: bank_app
    restart: unless-stopped
    build: .
    command: ["sh", "/code/scripts/start.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  db:
    image: postgres:13-alpine
    container_name: bank_db
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
