"""init

Revision ID: 8a8409a9560d
Revises: 
Create Date: 2020-07-01 21:53:10.360279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8a8409a9560d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallet",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("balance", sa.Numeric(), nullable=False),
        sa.CheckConstraint("balance >= 0"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "transaction",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("datetime", sa.DateTime(), nullable=True),
        sa.Column("wallet_id", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Numeric(), nullable=False),
        sa.CheckConstraint("amount != 0"),
        sa.ForeignKeyConstraint(["wallet_id"], ["wallet.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transaction_amount"), "transaction", ["amount"], unique=False
    )
    op.create_index(
        op.f("ix_transaction_datetime"), "transaction", ["datetime"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transaction_datetime"), table_name="transaction")
    op.drop_index(op.f("ix_transaction_amount"), table_name="transaction")
    op.drop_table("transaction")
    op.drop_table("wallet")
    # ### end Alembic commands ###
